# Generated by Django 5.2.5 on 2025-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
