# Generated by Django 5.2.5 on 2025-08-18 13:28

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='companies.region'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.region'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='companies.region')),
            ],
            options={
                'db_table': 'states',
                'unique_together': {('region', 'code')},
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='state_province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.state'),
        ),
    ]
