# Generated by Django 5.2.5 on 2025-08-19 07:42

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_country_alter_branch_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
