# Generated by Django 5.2.5 on 2025-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_region_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
        migrations.AlterField(
            model_name='company',
            name='state_province',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
