# Generated by Django 5.2.5 on 2025-08-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_region_alter_company_state_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state_province',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
