# Generated by Django 5.2.5 on 2025-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_role_created_at_role_description_role_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
